services:
  db:
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    build:
      context: .
      dockerfile: db.dockerfile

  mockoon:
    build:
      context: .
      dockerfile: Mockoon/Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./Mockoon:/Mockoon
    networks:
      - my-network

  front:
    develop:
      watch:
        - action: sync
          path: ./Front
          target: .
    build:
      context: .
      dockerfile: front.dockerfile
    ports:
      - "4200:4200"
    networks:
      - my-network

  back:
    develop:
      watch:
        - action: sync
          path: ./Back
          target: .
        - action: rebuild
          path: ./Back/pom.xml
    build:
      context: .
      dockerfile: back.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

networks:
  my-network:
    driver: bridge
  
volumes:
  db_data:
