name: back-project-oc
services:
  db:
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    build:
      context: .
      dockerfile: db.dockerfile

  mockoon:
    container_name: mockoon
    build:
      context: .
      dockerfile: Mockoon/Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./Mockoon:/Mockoon
    networks:
      - my-network

  front:
    container_name: front
    develop:
      watch:
        - action: sync
          path: ./Front
          target: .
    build:
      context: .
      dockerfile: front.dockerfile
    ports:
      - "4200:4200"
    networks:
      - my-network

  back:
    container_name: back
    develop:
      watch:
        - action: sync
          path: ./Back
          target: /app
        - action: rebuild
          path: ./Back/pom.xml
        - action: rebuild
          path: ./Back/src/main/resources/application.properties
    build:
      context: .
      dockerfile: back.dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
    name: db_data
