version: "3.7"
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwordxxx
      MYSQL_DATABASE: db
      MYSQL_USER: userr
      MYSQL_PASSWORD: passwordxxx
